
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Matt Koski", email = "maccam912@gmail.com"},
]
dependencies = [
    "streamlit>=1.23.1",
    "openai>=0.27.8",
]
requires-python = ">=3.11"
license = {text = "MIT"}
